# Generated by Django 5.0.6 on 2024-07-23 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_sensordata_billing_sensordata_kva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='meters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='product_id',
            field=models.ManyToManyField(related_name='assigned_users', to='capstone.meter'),
        ),
    ]
