# Generated by Django 5.0.6 on 2024-07-24 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_remove_customuser_product_id_remove_meter_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capstone.meter'),
        ),
    ]
