# Generated by Django 5.0.6 on 2024-07-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_customuser_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='user',
        ),
    ]
