# Generated by Django 5.0.6 on 2024-07-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_remove_customuser_meters_alter_meter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='last_alert_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
