# Generated by Django 5.0.6 on 2024-08-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_meter_last_alert_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
